services:
  mysql:
    image: mysql:8.0
    container_name: feedback-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbs_feedback
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - feedback-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: feedback-backend
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbs_feedback
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - feedback-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: feedback-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - feedback-net

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: feedback-ml-service
    ports:
      - "5000:5000"
    networks:
      - feedback-net

volumes:
  mysql_data:

networks:
  feedback-net:
